# Generated by Django 5.0 on 2023-12-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ddff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
